parameters:
  eye_on_hand: true
  freehand_robot_movement: false
  move_group: manipulator
  move_group_namespace: /
  namespcae: /handeyecalibration_eye_on_hand
  robot_base_frame: prbt_base_link
  robot_effector_frame: prbt_tool0
  tracking_base_frame: camera_link
  tracking_marker_frame: aruco_camera_marker
transformation:
  qw: 0.65385
  qx: 0.10940
  qy: -0.73791
  qz: -0.12646
  x: -0.0202
  y: -0.01560
  z: 0.02145